# Generated by Django 5.2.10 on 2026-01-12 13:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_documents', models.IntegerField(default=0)),
                ('processed_documents', models.IntegerField(default=0)),
                ('failed_documents', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'classification_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_id', models.CharField(max_length=255)),
                ('document_s3_bucket', models.CharField(max_length=255)),
                ('document_s3_key', models.CharField(max_length=1024)),
                ('document_filename', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('BUSINESS_LICENSE', 'Business License'), ('BANK_STATEMENT', 'Bank Statement'), ('VOIDED_CHECK', 'Voided Check'), ('TAX_RETURN', 'Tax Return'), ('DRIVERS_LICENSE', 'Drivers License'), ('ARTICLES_OF_INCORPORATION', 'Articles of Incorporation'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_by', models.CharField(blank=True, max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='document_classification.classificationjob')),
            ],
            options={
                'db_table': 'classification_result',
                'ordering': ['-created_at'],
            },
        ),
    ]
